name: meal_generator
description: "A Flutter application for generating personalized meal plans and recipes."
homepage: https://github.com/blackjoeyai-cpu/meal_generator
repository: https://github.com/blackjoeyai-cpu/meal_generator
issue_tracker: https://github.com/blackjoeyai-cpu/meal_generator/issues
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
