name: meal_generator
description: "A Flutter application for generating personalized meal plans and recipes."
homepage: https://github.com/blackjoeyai-cpu/meal_generator
repository: https://github.com/blackjoeyai-cpu/meal_generator
issue_tracker: https://github.com/blackjoeyai-cpu/meal_generator/issues
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9          # Calendar widget
  sqflite: ^2.3.0                # Local database (Android)
  path: ^1.8.3                   # Path manipulation utilities
  provider: ^6.0.5               # State management
  uuid: ^4.0.0                   # Unique ID generation
  shared_preferences: ^2.2.0     # Simple key-value storage
  intl: ^0.18.1                  # Date formatting
  url_strategy: ^0.2.0           # Web URL configuration

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.2               # Mocking framework for testing
  build_runner: ^2.4.6         # Code generation for mockito

flutter:
  uses-material-design: true
